config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  scope 'export-opportunities' do
    mount Sidekiq::Web => '/sidekiq'

    # site's root page
    root to: 'opportunities#index'

    get 'check' => 'application#check'
    get 'data_sync_check' => 'data_sync#check'
    get 'api_check' => 'application#api_check'
    get 'robots.txt' => 'robots_txts#show'
    get '/pingdom/ping' => 'application#ping'

    devise_for :users, module: 'users', skip: :sessions

    devise_scope :user do
      get '/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    end

    # Legacy sign in path
    get '/sign_in', to: redirect('export-opportunities/dashboard')

    devise_for :subscriptions,
               controllers: {
                confirmations: 'subscriptions',
               }

    get '/dashboard' => 'users/dashboard#index', as: 'dashboard'
    # get '/export-opportunities/dashboard/downloads' => 'users/downloads'
    scope '/dashboard', as: :dashboard do
      resources :enquiries, only: [:show], controller: 'users/enquiries'
      resources :downloads, only: [:show], controller: 'users/downloads'
    end

    # Legacy dashboard index page
    get '/dashboard/enquiries', to: redirect('export-opportunities/dashboard')

    resources :opportunities, only: [:show] do
      root action: 'results', as: ''
    end

    namespace :admin do
      get 'help', to: 'help#index'
      get 'help/:article_id', to: 'help#show'
      get 'help/:article_id/print', to: 'help#article_print', as: 'help_article_print'
      get 'help/:article_id/:section_id', to: 'help#article', as: 'help_article'

      devise_for :editors,
                 singular: :editor,
                 only: %i[registrations sessions passwords unlocks],
                 path_names: {
                   sign_up: 'new',
                 }

      devise_scope :editor do
        get '/editor/confirmation', to: 'confirmations#show', as: :editor_confirmation
        patch '/editor/confirmation', to: 'confirmations#update', as: :update_editor_confirmation

        put 'editors/reactivate/:id', to: 'registrations#reactivate', as: :editor_reactivate
        delete 'editors/deactivate/:id', to: 'registrations#destroy', as: :editor_deactivate
      end

      resources :editors, only: %i[index show edit update]

      resources :enquiries

      authenticated :editor do
        resources :enquiry_responses do
          get 'email_send', on: :collection
        end
      end

      resources :opportunities, only: %i[index show new create edit update] do
        authenticated :editor do
          collection do
            resources :downloads, only: %i[new create], controller: 'opportunity_downloads', as: :opportunity_downloads
          end

          resources :comments, only: %i[create], controller: 'opportunity_comments'
        end

        resource :status, only: %i[update destroy], controller: 'opportunity_status'
      end

      require 'constraints/flipper_admin_constraint'
      constraints FlipperAdminConstraint.new do
        flipper_block = -> { ExportOpportunities.flipper }
        mount Flipper::UI.app(flipper_block) => '/feature-flags'
      end

      resources :stats do
      end

      resources :reports do
        get 'impact_email' => 'reports_controller#impact_email'
      end

      get 'updates' => 'updates#index'

      root to: redirect('export-opportunities/admin/opportunities')
    end

    get '/enquiries/:slug' => 'enquiries#new', as: :new_enquiry
    post '/enquiries/:slug' => 'enquiries#create', as: :enquiries

    resources :company_details, only: [:index]

    resources :subscriptions, only: %i[create show destroy update]
    resources :pending_subscriptions, only: [:create]
    get '/pending_subscriptions/:id' => 'pending_subscriptions#update', as: :update_pending_subscription

    # for unsubscribing from emails, which can't normally handle delete method etc.
    get '/subscriptions/unsubscribe/:id' => 'subscriptions#destroy', as: :unsubscribe
    patch '/subscriptions/explain/:id' => 'subscriptions#update', as: :explain_unsubscribe

    resources :bulk_subscriptions, only: %i[index create]
    # for old emails, which may still have the v1 prefix
    # TODO: delete this when old subscription emails are sufficiently old
    get '/v1/subscriptions/unsubscribe/:id' => 'subscriptions#destroy'
    patch '/v1/subscriptions/explain/:id' => 'subscriptions#update'

    # Atom feed
    get '/feed', action: :index, controller: 'opportunities', format: 'atom'

    scope module: :v1, path: 'v1', constraints: { format: /json/ } do
      resources :opportunities, only: [:show] do
        collection do
          resource :count, controller: 'opportunities_count', only: [:show]
        end
      end
    end

    # Legacy admin sign in paths
    get '/users/sign_in', to: redirect('export-opportunities/admin/editors/sign_in'), as: nil
    # get '/users/sign_out', to: redirect('export-opportunities/admin/editors/sign_out'), as: nil
    get '/user/confirmation', to: redirect { |_params, request| "export-opportunities/admin/editor/confirmation?#{request.params.to_query}" }

    # Enquiry feedback
    get '/feedback', to: 'enquiry_feedback#new', as: :enquiry_feedback
    get '/feedback/opt_out', to: 'feedback_opt_outs#create', via: :get, as: :feedback_opt_out
    patch '/feedback/:id', to: 'enquiry_feedback#patch', as: :patch_enquiry_feedback

    # Error pages
    match '/500' => 'errors#internal_server_error', via: :all
    match '/404' => 'errors#not_found', via: :all

    # Mailer previews. This need to be declared explicitly or they get snapped up
    # by the wildcard rule below before Rails has a chance to route them
    # if Rails.env.development?
    get '/rails/mailers' => 'rails/mailers#index'
    get '/rails/mailers/*path' => 'rails/mailers#preview'
    # end


    get '/email_notifications/unsubscribe_all/:unsubscription_token', to: 'email_notifications#destroy', as: :delete_email_notifications
    patch '/email_notifications/unsubscribe_all/:unsubscription_token', to: 'email_notifications#update', as: :update_email_notification

    get '/api/cn/cpv', action: :search,
                       controller: 'api/cpv_lookup',
                       format: :json,
                       via: [:get]
    get '/api/profile_dashboard', action: :index, controller: 'api/profile_dashboard', format: 'json', via: [:get]
    get '/api/opportunities', action: :opportunities, controller: 'api/profile_dashboard', format: 'json', via: [:get]
    get '/api/activity_stream/', action: :index,
      controller: 'api/activity_stream', format: 'json', via: [:get] # Old route
    get '/api/activity_stream/enquiries', action: :enquiries,
      controller: 'api/activity_stream', format: 'json', via: [:get], as: :activity_stream_enquiries
    get '/api/activity_stream/opportunities', action: :opportunities,
      controller: 'api/activity_stream', format: 'json', via: [:get], as: :activity_stream_opportunities
    post '/api/document/', action: :create, controller: 'api/document'

    match '*path', to: 'errors#not_found', via: %i[get post patch put delete]

    match '(*path)',
          to: ->(_env) { [405, { 'Content-Type' => 'text/plain' }, ["\n"]] },
          via: [:options]
  end

  # site's root page
  get '', to: 'opportunities#index'

  get 'check' => 'application#check'
  get 'data_sync_check' => 'application#data_sync_check'
  get 'api_check' => 'application#api_check'
  get 'robots.txt' => 'robots_txts#show'

  # devise_for :users, module: 'users', skip: :sessions

  devise_scope :user do
    get '/sign_out', to: 'users/sessions#destroy'
  end

  # Legacy sign in path
  get '/sign_in', to: redirect('export-opportunities/dashboard')

  # devise_for :subscriptions,
  #            controllers: {
  #             confirmations: 'subscriptions',
  #            }

  get '/dashboard' => 'users/dashboard#index'
  # get '/export-opportunities/dashboard/downloads' => 'users/downloads'
  scope '/dashboard', as: :dashboard do
    resources :enquiries, only: [:show], controller: 'users/enquiries'
    resources :downloads, only: [:show], controller: 'users/downloads'
  end

  # Legacy dashboard index page
  get '/dashboard/enquiries', to: redirect('export-opportunities/dashboard')

  resources :opportunities, only: [:show] do
    root action: 'results'
  end

  namespace :admin do
    get 'help', to: 'help#index'
    get 'help/:article_id', to: 'help#show'
    get 'help/:article_id/print', to: 'help#article_print'
    get 'help/:article_id/:section_id', to: 'help#article'

    # devise_for :editors,
    #            singular: :editor,
    #            only: %i[registrations sessions passwords unlocks],
    #            path_names: {
    #              sign_up: 'new',
    #            }

    devise_scope :editor do
      get '/editor/confirmation', to: 'confirmations#show'
      patch '/editor/confirmation', to: 'confirmations#update'

      put 'editors/reactivate/:id', to: 'registrations#reactivate'
      delete 'editors/deactivate/:id', to: 'registrations#destroy'
    end

    resources :editors, only: %i[index show edit update]

    resources :enquiries

    authenticated :editor do
      resources :enquiry_responses do
        get 'email_send', on: :collection
      end
    end

    resources :opportunities, only: %i[index show new create edit update] do
      authenticated :editor do
        collection do
          resources :downloads, only: %i[new create], controller: 'opportunity_downloads'
        end

        resources :comments, only: %i[create], controller: 'opportunity_comments'
      end

      resource :status, only: %i[update destroy], controller: 'opportunity_status'
    end

    require 'constraints/flipper_admin_constraint'
    constraints FlipperAdminConstraint.new do
      flipper_block = -> { ExportOpportunities.flipper }
      mount Flipper::UI.app(flipper_block) => '/feature-flags'
    end

    resources :stats do
    end

app/models/opportunity.rb
require 'elasticsearch'

class Opportunity < ApplicationRecord
  include Elasticsearch::Model
  index_name [base_class.to_s.pluralize.underscore, Rails.env].join('_')

  # built in callbacks won't work with our custom indexed taxonomies
  after_commit on: [:create] do
    unless expired?
      __elasticsearch__.index_document
    end
  end

  after_commit on: [:update] do
    if exists_in_elasticsearch?
      __elasticsearch__.delete_document
    end
    unless expired?
      __elasticsearch__.index_document
    end
  end

  after_commit on: [:destroy] do
    if exists_in_elasticsearch?
      __elasticsearch__.delete_document
    end
  end

  before_commit on: %i[create update] do
    sanitise_description
  end

  settings index: { max_result_window: 100_000 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english'
      indexes :teaser, analyzer: 'english'
      indexes :description, analyzer: 'english'

      indexes :types do
        indexes :slug, type: :keyword
      end

      indexes :values do
        indexes :slug, type: :keyword
      end

      indexes :countries do
        indexes :slug, type: :keyword
      end

      indexes :sectors do
        indexes :slug, type: :keyword
      end

      indexes :cpvs do
        indexes :industry_id, type: :keyword
      end

      indexes :response_due_on, type: :date
      indexes :first_published_at, type: :date
      indexes :updated_at, type: :date
      indexes :status, type: :keyword
      indexes :source, type: :keyword
    end
  end

  has_paper_trail versions: { class_name: 'OpportunityVersion' },
                  only: [:status]

  extend FriendlyId
  friendly_id :title, use: %i[slugged finders]

  CONTACTS_PER_OPPORTUNITY = 2
  paginates_per 25
  TITLE_LENGTH_LIMIT = 250.freeze
  TEASER_LENGTH_LIMIT = 140.freeze

  enum status: { pending: 1, publish: 2, draft: 3, trash: 4 }
  enum ragg: { undefined: 0, blue: 2, green: 4, amber: 6, red: 8 }
  enum source: { post: 0, volume_opps: 1, buyer: 2 }
  enum original_language: { en: 0, de: 1, es: 2, fr: 3, it: 4, nl: 5, pl: 6 }

  enum request_type: { goods: 0, services: 2 }
  enum request_usage: { samples: 0, sell_goods: 2, use_product: 4 }
  enum enquiry_interaction: { post_response: 0, third_party: 2 }

  include PgSearch::Model

  pg_search_scope :fuzzy_match,
                  against: %i[title teaser description],
                  using: { tsearch: { tsvector_column: 'tsv', dictionary: 'english' } }

  pg_search_scope :admin_match,
                  against: %i[title teaser description],
                  associated_against: { author: %i[name email] },
                  using: { tsearch: { tsvector_column: 'tsv', dictionary: 'english' } }

  scope :published, -> { where(status: Opportunity.statuses[:publish]) }
  scope :applicable, -> { where('response_due_on >= ?', Time.zone.today) }
  scope :drafted, -> { where(status: Opportunity.statuses[:draft]) }

  belongs_to :service_provider, optional: false
  belongs_to :author, class_name: 'Editor', optional: false
  has_and_belongs_to_many :countries
  has_and_belongs_to_many :sectors
  has_and_belongs_to_many :types
  has_and_belongs_to_many :values
  has_and_belongs_to_many :supplier_preferences
  has_many :contacts, dependent: :destroy
  has_many :comments, -> { order(:created_at) }, class_name: 'OpportunityComment', inverse_of: :opportunity
  has_many :enquiries, dependent: :nullify
  has_many :subscription_notifications, dependent: :destroy
  has_many :opportunity_checks, dependent: :destroy
  has_many :opportunity_sensitivity_checks, dependent: :destroy
  has_many :cpvs, foreign_key: 'opportunity_id', class_name: 'OpportunityCpv', dependent: :destroy

  accepts_nested_attributes_for :contacts, reject_if: :all_blank

  validates :title, presence: true, length: { maximum: TITLE_LENGTH_LIMIT }
  validate :teaser, :teaser_validations
  validates :response_due_on, presence: true
  validate :contacts, :contact_validations
  validate :target_url, :enquiry_url_validations
  validates :slug, presence: true, uniqueness: true

  def enquiry_url_validations
    if source == 'post' && custom_url_service_provider?
      if not_a_url?(target_url)
        errors.add(:target_url, 'The custom target enquiry URL is not a valid URL. A valid URL starts with http:// or https://')
      end
    end
  end

  def contact_validations
    if source == 'post'
      errors.add(:contacts, "Contacts are missing (#{CONTACTS_PER_OPPORTUNITY} are required)") if contacts.length < CONTACTS_PER_OPPORTUNITY
    end
  end

  def teaser_validations
    if source == 'post'
      if teaser.present?
        errors.add(:teaser, "can't be more than #{TEASER_LENGTH_LIMIT}") if teaser.length > TEASER_LENGTH_LIMIT
      else
        errors.add(:teaser, 'is missing')
      end
    end
  end

  # Database triggers to make Postgres rebuild its fulltext search
  # index whenever an opportunity is created or updated
  trigger.before(:insert, :update).for_each(:row).nowrap do
    "tsvector_update_trigger(tsv, 'pg_catalog.english', title, teaser, description);"
  end

  def slug=(slug)
    return if slug.nil?

    self[:slug] = slug.parameterize
  end

  # The authors of `pg_search` would prefer a nil value to return an empty set
  # https://github.com/Casecommons/pg_search/issues/49
  def self.search(query)
    results = all
    results = results.fuzzy_match(query) if query.present?
    results
  end

  # removing nbsp and other breaking characters
  def sanitise_description
    self.description = description.try(:gsub, /[[:space:]]+/, ' ').try(:gsub, /&nbsp;/i, ' ')
  end

  def as_indexed_json(_ = {})
    as_json(
      only: %i[title teaser description created_at updated_at status response_due_on first_published_at source],
      include: {
        countries: { only: :slug },
        types: { only: :slug },
        sectors: { only: :slug },
        values: { only: :slug },
        cpvs: { only: :industry_id },
      }
    )
  end

  def to_param
    slug || id
  end

  def expired?
    response_due_on < Time.zone.today
  end

  def published?
    status == :publish
  end

  def custom_url_service_provider?
    service_provider && service_provider.name == 'DFID'
  end

  def not_a_url?(target_url)
    return false if target_url.blank?

    target_url.downcase.match(%r{^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$}).blank?
  end

  def tender?
    false
  end

  def exists_in_elasticsearch?
    Opportunity.__elasticsearch__.client.exists? index: Opportunity.index_name, type: 'opportunity', id: id
  end
end

app/controllers/v1/opportunities_controller.rb
class V1::OpportunitiesController < V1::BaseController
  def show
    @result = OpportunityFinder.new.call(id)

    if @result.success?
      render :show
    else
      render_error(@result.error, @result.code)
    end
  end

  private

    def id
      params.require(:id)
    end
end

app/helpers/opportunity_helper.rb
module OpportunityHelper
  def opportunity_status_link(string)
    case string
    when 'publish' then 'Published'
    when 'trash' then 'Trashed'
    when 'pending' then 'Pending'
    when 'draft' then 'Draft'
    else
      string.to_s.titleize
    end
  end

  def filtered_admin_opportunities_path
    admin_opportunities_path(session[:opportunity_filters])
  end
end

app/views/admin/opportunities/_comment_form.html.haml
= form_for @comment_form, url: admin_opportunity_comments_path(@opportunity), html: { class: 'comment-form' } do |f|
  .field.textarea
    = f.label :message, 'Add a comment', { 'aria-describedby': 'opportunity-comment-field-description' }
    %p.description{ id: 'opportunity-comment-field-description' }
      Comments posted here are only visible by you and other editors.
    = f.text_area :message, { rows: 8, cols: 60 }

  = f.submit 'Add Comment', class: 'button add'
  %span.separator or
  - if current_editor.administrator?
    = f.submit 'Return to draft with comment', class: 'button draft'

app/views/admin/opportunities/_form.html.haml
- form = FormPresenter.new(content, {})
- opp = AdminOpportunityPresenter.new(self, @opportunity, content)

:javascript
  dit.constants.CPV_FIELD_PLACEHOLDER = "#{content['enhanced_cpv_field_placeholder']}";

%section.process
  .container
    %h2= content['group_2_title']

    - if @opportunity.errors.any?
      .errors
        %p#errors-list-label
          = pluralize(@opportunity.errors.count, 'error')
          prevented this opportunity from being saved:
        %ul{'aria-labelledby': 'errors-list-label'}
          - @opportunity.errors.full_messages.each do |message|
            %li= message

    = form_for [:admin, @opportunity], :builder => TemplateFormBuilder do |f|
      %p= content['group_2_description']
      = f.input_text :title, form.input_text('title'), { maxlength: '80', required: true }

      - if @opportunity.errors[:slug].any?
        = f.input_text :slug, form.input_text('slug'), required: true

      = f.input_text :teaser, form.input_text('teaser'), { maxlength: '150', required: true }
      = f.input_textarea :description, form.input_textarea('description'), { rows: '12', required: true }

      = render partial: 'forms/input_label', locals: { label: form.input_label('sign_off') }
      %fieldset.field.field-sign-off
        - opp.sign_off_content(@service_provider).each_with_index do |line, index|
          = content_tag("p", line)

      -# Workaround because value_ids should be a single value rather than an Array.
      - attrs = {}
      - if @opportunity.value_ids.present?
        - attrs = { default: @opportunity.value_ids[0] }
      = f.input_radio :value_ids, form.input_radio('values', @values), attrs

      = f.input_select :country_ids, form.input_select('countries', @countries), { default: @default_country, multiple: true, size: '5', data: { node: 'countries', unselected: content['countries_unselected'], display: content['countries_selected_title'] } }
      = f.input_select :sector_ids, form.input_select('sector_ids', @sectors), { multiple: true, size: '5', data: { node: 'sectors', unselected: content['sectors_unselected'], display: content['sectors_selected_title'] } }
      = f.input_text_group :cpv_ids, form.input_text_group('cpvs'), { data: { node: 'cpv-lookup' }, edit_opportunity: @opportunity.cpvs.present? }

      = f.input_checkbox_group :type_ids, form.input_checkbox_group('types', @types)
      = f.input_checkbox_group :supplier_preference_ids, form.input_checkbox_group('supplier_preferences', @supplier_preferences)
      = f.input_date_month_year :response_due_on, form.input_date_month_year('response_due_on'), required: true
      = f.input_select :service_provider_id, form.input_select('service_provider_id', @service_providers), { default: @service_provider.id, required: true }

      = f.input_text :target_url, form.input_text('target_url'), data: { node: 'target-url' }
      = f.fields_for :contacts do |field|
        - required = field.index < 1
        = field.input_text :name, form.input_text("contact_#{field.index + 1}_name"), required: required
        = field.input_text :email, form.input_text("contact_#{field.index + 1}_email"), required: required

      - if policy(@opportunity).show_ragg? && @opportunity.id.present?
        = f.input_radio :ragg, form.input_radio('ragg', @ragg)

      .controls
        %input{ type: 'submit', name: 'commit', value: form.content['submit_create'], class: 'button' }

        - if current_page?(action: 'new')
          %span or
          %input{ type: 'submit', name: 'commit', value: form.content['submit_draft'], class: 'button draft' }

app/views/admin/opportunities/_history.html.haml
%section.history
  .container
    %h2 History and comments

    - if @history.any?
      - @history.each do |item|
        = render item
    - else
      %p.version-unavailable= t('admin.opportunity.history.unavailable')

    = render 'comment_form'

app/views/admin/opportunities/edit.html.haml
- content_for :action_specific_head  do
  = stylesheet_link_tag 'transformation_admin/pages/opportunity'
  = javascript_include_tag 'transformation/dit.page.form'
  = javascript_include_tag 'transformation_admin/dit.page.opportunity'


%section.intro
  %h1= content['title_edit']
  %p.mandatory= content['mandatory']

= render  partial: 'form', locals: { opportunity: @opportunity, content: content }
= render 'history'

app/views/admin/opportunities/index.html.haml
- content_for :action_specific_head  do
  = stylesheet_link_tag 'transformation_admin/pages/opportunity_index'
  = javascript_include_tag 'transformation_admin/dit.page.opportunity_index'


%section.intro
  .container
    %h1 Opportunities

    .controls
      .filters
        %p
          Filter by status:
          - if @filters.selected_status.nil?
            %span All
          - else
            - @available_status.each do |name, _|
              - if name.to_s == @filters.selected_status.to_s
                %span= opportunity_status_link(name)

        %ul
          - if !@filters.selected_status.nil?
            %li= link_to('All', admin_opportunities_path(hide_expired: @filters.hide_expired, s: @filters.raw_search_term))
          - @available_status.each do |name, _|
            - if name.to_s != @filters.selected_status.to_s
              %li= link_to(opportunity_status_link(name), admin_opportunities_path(hide_expired: @filters.hide_expired, status: name, s: @filters.raw_search_term))

      .displayed
        %p
          - if @filters.hide_expired
            %span
              Expired opportunities are
              %strong hidden
            = link_to 'Show expired opportunities', session[:opportunity_filters].merge(hide_expired: false)
          - else
            %span
              Expired opportunities are
              %strong shown
            = link_to 'Hide expired opportunities', session[:opportunity_filters].merge(hide_expired: nil)


      .actions
        = link_to 'New opportunity', new_admin_opportunity_path, class: 'button'
        = link_to 'Download', new_admin_opportunity_download_path, class: 'button'


    .search
      = form_tag admin_opportunities_path, method: :get do
        - if @filters.selected_status
          = hidden_field_tag 'status', @filters.selected_status

        - if !@filters.hide_expired
          = hidden_field_tag 'hide_expired', false

        = text_field_tag 's', @filters.raw_search_term, placeholder: 'Search opportunities', class: 'text'
        = submit_tag 'Search', class: 'button'

%section.results
  .container
    %table
      %thead
        - if policy(@opportunities).show_ragg?
          %th.ragg
            Editor
        %th.title
          = sortable(:opportunity_filters, 'title', 'Title', 'asc', @filters.sort)
        %th.status
          = sortable(:opportunity_filters, 'status', 'Status', 'asc', @filters.sort)
        %th.provider
          = sortable(:opportunity_filters, 'service_provider_name', 'Service provider', 'asc', @filters.sort)
        %th.enquiries
          = sortable(:opportunity_filters, 'enquiries_count', 'Enquiries received', 'desc', @filters.sort)
        %th.created
          = sortable(:opportunity_filters, 'created_at', 'Created date', 'desc', @filters.sort)
        %th.published
          = sortable(:opportunity_filters, 'first_published_at', 'First published', 'desc', @filters.sort)
        %th.language
          =sortable(:opportunity_filters, 'original_language', 'Original language', 'desc', @filters.sort)
        %th.source
          =sortable(:opportunity_filters, 'source', 'Source', 'asc', @filters.sort)
        %th.feed
          =sortable(:opportunity_filters, 'tender_source', 'Feed', 'asc', @filters.sort)
        %th.response
          = sortable(:opportunity_filters, 'response_due_on', 'Expiry date', 'asc', @filters.sort)

      %tbody
        - @opportunities.each do |opportunity|
          %tr
            - if policy(@opportunities).show_ragg?
              %td{ class: "ragg ragg-#{opportunity.ragg}" }
                %span The triage rating is #{opportunity.ragg}

            %td.title
              - opportunity_link_text = opportunity.title.present? ? opportunity.title : '(no title)'
              = link_to opportunity_link_text, admin_opportunity_path(opportunity)
              - if opportunity.expired?
                %small.expired (expired)

            %td.status
              = opportunity_status_link(opportunity.status)
            %td.provider
              = opportunity.service_provider&.name
            %td.enquiries
              = opportunity.enquiries.size
            %td.created
              = opportunity.created_at.to_s(:admin_short_date)
              %br
              %small= opportunity.created_at.to_s(:admin_short_time)
            %td.published
              = opportunity.first_published_at&.to_s(:admin_short_date)
              %br
              %small= opportunity.first_published_at&.to_s(:admin_short_time)
            %td.language
              = opportunity.original_language
            %td.source
              = opportunity.source
            %td.feed
              = opportunity.tender_source
            %td.response
              = opportunity.response_due_on.to_s(:admin_date)

    = render partial: "components/pagination", locals: { items: @opportunities }

app/views/admin/opportunities/new.html.haml
- content_for :action_specific_head  do
  = stylesheet_link_tag 'transformation_admin/pages/opportunity'
  = javascript_include_tag 'transformation/dit.page.form'
  = javascript_include_tag 'transformation_admin/dit.page.opportunity'


%section.intro
  %h1= content['title_new']
  %p.mandatory= content['mandatory']

= render  partial: 'form', locals: { opportunity: @opportunity, content: content }
 
%section.help
  .container
    %h2= content['help_title']
    = link_to content['help_link'], '/admin/help/how-to-write-an-export-opportunity/overview'